application: mu-api
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:

- url: /system
  static_dir: musicapi/system

- url: /application
  static_dir: musicapi/application

- url: .*
  script: index.php


